### ISSUE TITLE
Notification Mails detected as SPAM

### ISSUE THREAD

**Issue by dasGoogle** [ephios-dev/ephios#1077]
**Describe the bug**
This is likely specific to the exact email setup users have but in my case, the notification mails in my case are caught by the SpamAssassin rule `TO_NO_BRKTS_HTML_IMG` which is discussed [here](https://stackoverflow.com/questions/40082594/meaning-of-to-no-brkts-html-img-in-spamassassin). As a fix for this, it would be useful if ephios used the configured first and last name to properly address the users in the `To:` field of the email.   

**To Reproduce**
Make ephios send a notification email.

**Expected behavior**
Emails should arrive in my inbox without being detected as SPAM. This could be done by modifying the `To:` field. 

**Screenshots**
\-

**Environment**
An email SPAM filter using SpamAssassin

**Additional context**
\-

**Comment by felixrindt** [comment]
You mentioned more factors in other channels like only having one embedded image. Can you explain that here too?

**Comment by dasGoogle** [comment]
Basically, all my knowledge comes from the StackOverflow thread linked in the initial issue, which also goes into a single image and an HTML MIME part being in the mail.

**Comment by felixrindt** [comment]
@dasGoogle can you please check #1078 resolved your issue?

**Comment by dasGoogle** [comment]
Just deployed the new Docker container and it works perfectly. Receiving HTML and Plain Text mails without any SPAM flags. Thanks for the quick fix!
