### ISSUE TITLE
Guest registration doesn't work

### ISSUE THREAD

**Issue by pov91** [ephios-dev/ephios#1172]
**Describe the bug**
If you want to register as a guest for an event using the generated link, you always get the error message that you are already registered as a guest, even if you are not: "Sie sind bereits als Gast für diese Veranstaltung registriert." It is not possible at the moment to register for gestures at events.

**To Reproduce**
Create an event and allow guests. Call up the generated link and fill out the form and submit it.

**Expected behavior**
It should be possible to register new guests for an event.

**Screenshots**
![Unbenannt](https://github.com/ephios-dev/ephios/assets/89405194/9f8d6a90-b66b-4af8-ac1a-7ded32c23444)

**Environment**
Browser Client: Firefox 121.0, Firefox 120.0.1, Firefox mobile 121.0 and Chromium 110.0.5470.0
OS Client: Windows 11, Android 14, Linux Mint 21.2
OS Server: Ubuntu 22.04.3 LTS (Kernel 5.15.0-91)
Database: MariaDB 10.6.12
Python-Version: 3.10.12
Ephios-Version: v0.15.18

**Comment by felixrindt** [comment]
I wasn't able to reproduce this on our staging server given your instructions. I'll test with an environment like yours next.

**Comment by felixrindt** [comment]
Even with mariadb 10.6 I could not reproduce the behavior you are seeing (with a freshly migrated database). The culprit seem to be the following lines:

https://github.com/ephios-dev/ephios/blob/15204d40a1a1da86f32dcc4459adbe0034171384/ephios/plugins/guests/views.py#L66-L78

I think you are getting an Integrity Error for some reason. @pov91 Could you try inserting a line using the db shell and posting the output? Should look something like

```bash
# in your ephios python env
python -m ephios dbshell
MariaDB [ephios]>  INSERT INTO `guests_guestuser` VALUES (10000,'test@example.com','2000-01-01','','7dcW_Hd-RUv_QovqYDBnVF8MVH748sCTHCL_iIhYcm8','2024-01-04 14:00:39.088011',1,'Testname');
```

I get a `Query OK, 1 row affected (0,011 sec)`, but you should be getting something else. If it does work for you however, remember to delete the tuple again.

**Comment by pov91** [comment]
I think I found the error. I suspect it has to do with the change from first name with last name to a display name. I can read the following fields in my database:
![Unbenannt](https://github.com/ephios-dev/ephios/assets/89405194/3c0220fe-6f84-42dc-aa08-a6cbd73e955a)

Compared to the schema above in what I should try out, the fields “first_name” and “last_name” are too many. If you read out the fields with "SELECT xyz FROM guests_guestuser;", all fields are filled with content, Except the "display_name" field only shows empty rows.

Could this be the problem? If so, what would be the best way to convert that safely?

**Comment by felixrindt** [comment]
> I think I found the error. I suspect it has to do with the change from first name with last name to a display name. I can read the following fields in my database: ![Unbenannt](https://private-user-images.githubusercontent.com/89405194/294301362-3c0220fe-6f84-42dc-aa08-a6cbd73e955a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDg1NjMsIm5iZiI6MTcwNDQwODI2MywicGF0aCI6Ii84OTQwNTE5NC8yOTQzMDEzNjItM2MwMjIwZmUtNmY4NC00MmRjLWFhMDgtYTZjYmQ3M2U5NTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDIyNDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNjFmNjBlMmZkNmU3ZDVlMzg5MjUyNTkyMGIzYzg1MmZjZWM3ODNjMDM3MWQ0YmI2ZDM4ZjFkOTQ0OTczYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IUwpaJ6sR7yRmeim9BMk4lgpakPnXA8mIpec7-elQ7Y)
> 
> Compared to the schema above in what I should try out, the fields “first_name” and “last_name” are too many. If you read out the fields with "SELECT xyz FROM guests_guestuser;", all fields are filled with content, Except the "display_name" field only shows empty rows.
> 
> Could this be the problem? If so, what would be the best way to convert that safely?

This indeed looks like you messed up migrating when upgrading a version. Might be related to the problem, as the check is based on some combined unique check, but I'm unsure about it.

Can you post the output of `python -m ephios migrate --fake`?

**Comment by pov91** [comment]
I ran "python -m ephios migrate" after every update. Here is the output of "python -m ephios migrate --fake":
![Unbenannt2](https://github.com/ephios-dev/ephios/assets/89405194/cea1074f-4dba-4539-ac9c-153c7f5f986d)

When I try to run the migration again, the following output comes:
![Unbenannt3](https://github.com/ephios-dev/ephios/assets/89405194/87da3654-4521-4fcb-a418-7f2b3b7b8a61)

The database structure is still unchanged and it still has first and last name fields.

**Comment by felixrindt** [comment]
Seems like you missed migrating when you did your last update. Unfortunately I just made it hard for you to run the migrations now. Let’s revert faking it and apply it for real. Please do a backup before this.

python -m ephios migrate —fake guests 0004_alter_guestparticipation_options_and_more
python -m ephios migrate guests

**Comment by pov91** [comment]
Seems not to work:
![Uploading Unbenannt4.png…]()
