### ISSUE TITLE
Event Title is not Clickable

### ISSUE THREAD

**Issue by BenBals** [ephios-dev/ephios#1220]
**Is your feature request related to a problem? Please describe.**
I was confused since the title of an event at `/events/` is not clickable. I clicked it multiple times until I found out I had to use the "Show" button.

![Screenshot 2024-03-08 at 14 47 34](https://github.com/ephios-dev/ephios/assets/2546622/6c69ed85-a2b9-48ab-ad3e-714805b7fc4c)
*Figure 1: Me selecting the event title because I tried to use it as a button.*

**Describe the solution you'd like**
Clicking the name of an event has the same effect as using the "Show" button

**Describe alternatives you've considered**
Alternatively, move the show button to the left to make it more obvious.

**Additional context**
n/a

**Comment by felixrindt** [comment]
It is clickable on a smaller screen. I agree though we could make it more like GitHub notifications and ditch the show button.
