### ISSUE TITLE
Copying events with overnight shifts creates broken copies

### ISSUE THREAD

**Issue by lukasrad02** [ephios-dev/ephios#1250]
**Describe the bug**
When copying an event with shifts overnight to the next day, these shifts are created with wrong times.

**To Reproduce**

1. Create an event with the following shifts (as shown in the screenshot "original event")
    - 22:30-23:30 ("normal shift")
    - 23:30-00:30 ("overnight shift")
2. Create a copy of the event to the same day (using the configuration from the screenshot)
3. In contrast to the original event that ends at 01:00 (end of the overnight shift), the copy ends at 23:30 (end of the normal shift), as shown in the screenshots. However, the individual shift are both shown correctly on the copy.
4. The incorrect shift data also beaks the single day calendar view (see screenshot)

**Expected behavior**
When copying an event, all shifts including overnight shifts should be copied according to their configuration on the original event. The end time of the copied event should be identical to the end time of the latest shift end time.

**Screenshots**
Original event:  
![Original event](https://github.com/ephios-dev/ephios/assets/49586507/b29dad03-591d-46dc-ae6b-0327144df341)

Copy configuration:  
![Copy configuration](https://github.com/ephios-dev/ephios/assets/49586507/3fabb73b-13c1-4ddc-bf9e-501be1523ecf)

Copied event:  
![Copied event](https://github.com/ephios-dev/ephios/assets/49586507/abdef488-fb61-4b0a-9246-194155b5840e)

Broken single day calendar view:  
![Broken calendar view](https://github.com/ephios-dev/ephios/assets/49586507/5c5d86f8-e71e-4c52-802f-047bbb89aeee)

**Environment**
Tested with:
- ephios v0.16.3 (docker deployment with Postgres 12)
- ephios on commit 5025baa (local development instance with SQLite)

Both times using Firefox 124.0.1

**Additional context**
When editing the overnight shift on the copy event and saving it unchanged (i.e., just visiting the edit view and clicking save), the event seems to be fixed as issues described above can't be observed afterwards.

**Comment by felixrindt** [comment]
I was able to reproduce the issue you described and prepared a fix in #1252. Came down to using the wrong timezone when handling the times.
