### ISSUE TITLE
Support Name Titles

### ISSUE THREAD

**Issue by felixrindt** [ephios-dev/ephios#146]
**Is your feature request related to a problem? Please describe.**

My name is Dr. Lilly Mayer, so I put "Lilly" as my given name and "Dr. Mayer" as my last name. 
In some places, my name is displayed as "Lilly Dr. Mayer", which I find strange.

**Describe the solution you'd like**
I want my name to be displayed as "Dr. Lilly Mayer".
I want to input my title separately from my last name.

**Describe alternatives you've considered**

* let user choose a display string. That would support nicknames as well, but could differ a lot from first/last names shown in other places.
* support multiple naming schemes like pretix does.

**Comment by jeriox** [comment]
could you link to/explain the "multiple naming schemes" thing?
+1 in general.
We could also think of Anreden at this point.

**Comment by felixrindt** [comment]
pretix blog post about name schemes: https://pretix.eu/about/en/blog/20181109-release-220/
A simple Title field should be fine though

Could we avoid Anreden and the complexity of gender by sticking to "Hello {user}"?

**Comment by jeriox** [comment]
> By now and after having read https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/ multiple times I think something like "display name" and "full name" might be what I want

that would map to Felix being your display name and Felix Rindt being your full name?

**Comment by felixrindt** [comment]
> > By now and after having read https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/ multiple times I think something like "display name" and "full name" might be what I want
> 
> that would map to Felix being your display name and Felix Rindt being your full name?

depends really on what people prefer or what seems to be the standard in their organization. Display name is the one used to display the user in all kinds of views and email templates.

The full_name might be used for search, exporting certificates, etc. (I don't think we have much use for it now).

We could even have a seperate greeting (name), if people want to be greeted with a different name (e.g. in emails) than shown to other users.
