### ISSUE TITLE
Expiration date of qualification grant wrong on profile page

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#170]
On the production instance the expiration date of the class C1 drivers licence is wrong on the profile page of two users. The correct date is set and displayed while editing the user profile. The problem seems to be somewhere in the `qualifications()` method on the user profile:

```
>>> u.qualificationgrant_set.all()[1]
<QualificationGrant: Fahrerlaubnis Klasse C1, user@mail.tld>
>>> u.qualificationgrant_set.all()[1].expires
datetime.datetime(2022, 8, 21, 22, 0, tzinfo=<UTC>)
>>> u.qualifications[1]
<Qualification: Fahrerlaubnis Klasse C1>
>>> u.qualifications[1].expires
datetime.datetime(2047, 10, 7, 23, 0, tzinfo=<UTC>)
```

**Comment by felixrindt** [comment]
Ok that one looks crazy
