### ISSUE TITLE
Filter event list

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#232]
As a user, I expect the event list to offer the follwing filters:

- event type
- search field

Possible filters (consider keeping the UI slight)
- state of my participation / can I sign up?
- calendar (prior to/after selected date)

**Comment by felixrindt** [comment]
Maybe we could also have "past events" in the same view, using filters to look at the past.
We do have a permission for past events, I would opt for dropping it, though. Why do we need it @jeriox ?

**Comment by jeriox** [comment]
It was requested by the JUH planner that normal users should not be able to view past events, so the permission was our compromise to support both ways. I can ask if that is still required and what the motivation was for that decision.
