### ISSUE TITLE
New signup method "pot of qualifications"

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#234]
##### Qualifizierungstopf (HiOrg-like)

Wenn man einen Mix aus Qualifizierungen brauch, aber keine festen Anzahlen und Einteilungen macht, kann man dieses Verfahren verwenden. Dabei gibt man Qualifikationen an und dazu, wie oft man diese jeweils wenigstens braucht. 

Ein Helfer kann sich registrieren, wenn er irgendeine der Qualifikationen hat. Die Bestätigung erfolgt durch einen Verantwortlichen des Events.

**Comment by felixrindt** [comment]
now regarded as duplicate to #11.
