### ISSUE TITLE
Send push notifications

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#236]
As a user, I expect the application to send notifications via the Notifications API (https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) once I enable them. I expect to receive notifications for the same things that I receive emails for.
This could be implemented by https://github.com/safwanrahman/django-webpush

This could also be combined with #237 with https://pypi.org/project/django-pwa-webpush/

**Comment by jeriox** [comment]
We should reconsider our messaging approach within this issue. Currently, we are sending synchronous mails (in the worst case to all users). So first we need an email backend that sends asynchronous mails, e.g. https://pypi.org/project/django-mailer/ or https://github.com/pmclanahan/django-celery-email

On the other hand, it would be better to use a flexible messaging framework for all events. Our core code as well as plugins should be able to register a set of events/notifications (e.g. participation state changes, user data changes, consequence is decided). The user should be able to decide on which channels (mail, push notification, more channels via pluign) he wants to receive which notification.
I started to research frameworks for this purpose and came across the following:

- https://github.com/django-notifications/django-notifications has the right concept but is meant for in-site notifications (no support for backends at all)
- https://github.com/pinax/pinax-notifications looks exactly like what we want, but I'm not sure whether one can use it outside of pinax. also only the email backend is implemented, we would need to do the others on our own
- https://github.com/worthwhile/django-herald uses seperate classes for the different services (EmailMessage, TwilioMessage) which is not what we want
- https://github.com/idlesign/django-sitemessage looks kinda good, different message types and different backends

Of course we could also implement our own solution

**Comment by felixrindt** [comment]
I have some points to make on how to handle email :)

**Comment by jeriox** [comment]
So I had a closer look at the frameworks mentioned earlier. Out of those, only pinax-notifications is suitable for our needs. Downside: they rely on the django sites framework which we don't use. Also the construction was not perfect as they focus more on fixed notifications (where the text of a notification is predefined and additionial content is only a small feature). For us, notifications usually depend heavily on the actual state of something. So I decided to build it on my own.

**Comment by felixrindt** [comment]
Are you building it as a seperate app? Also, how do we want to deal with notifications for non-local participants?

**Comment by jeriox** [comment]
no, I am not. 
I decided to do that out of the notification framework as this is really inconvenient. we only have an email adress for those participants, but some backends will not use an email address to reach the user
