### ISSUE TITLE
New signup method "complex requirements"

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#243]
This is meant to be a general purpuse signup methods for complex requirements, esp. dealing with various counts of different qualifications and people. 

Further specification in the design blog.

**Comment by felixrindt** [comment]
The blocks editor is prepared by now. Besides the main open task of implementing it as a shift structure, these are some additional points to consider:

* [ ] Vue production version 
* [ ] Vue CSP 
* [ ] unify how required qualifications are rendered accross shift structures
