### ISSUE TITLE
Event slugs in event url

### ISSUE THREAD

**Issue by felixrindt** [ephios-dev/ephios#301]
Lets get urls like `/events/immergut-festival-42` where 42 is the event pk and the slug is derived from the title. 
Could use `django-braces` or a custom implementation to redirect to a canonical slug, should the title change.

**Comment by jeriox** [comment]
Would love this for event creation as well. (events/create/training)

**Comment by felixrindt** [comment]
> Would love this for event creation as well. (events/create/training)

`training` being the event type slug? You think it's ok to not have the pk in there (in case event type name changes?)

**Comment by jeriox** [comment]
> > Would love this for event creation as well. (events/create/training)
> 
> `training` being the event type slug? You think it's ok to not have the pk in there (in case event type name changes?)

yeah probably the pk should be there. but if the name changes the old link is invalid either way

**Comment by felixrindt** [comment]
> > > Would love this for event creation as well. (events/create/training)
> > 
> > 
> > `training` being the event type slug? You think it's ok to not have the pk in there (in case event type name changes?)
> 
> yeah probably the pk should be there. but if the name changes the old link is invalid either way

Well you could just redirect to the correct slug by just using the pk to identify the object. That's what the braces mixin does.
