### ISSUE TITLE
Proper logging setup

### ISSUE THREAD

**Issue by felixrindt** [ephios-dev/ephios#349]
We should provide proper logging configuration in `settings.py`. See https://docs.djangoproject.com/en/3.1/topics/logging/#configuring-logging

**Comment by jeriox** [comment]
The AdminEmailHandler is currently working fine, meaning we are notified about all ERROR messages. We could enable logging of INFO or WARNING messages to the console and let uWSGI log them to its logfile (as in https://stackoverflow.com/questions/46747036/which-django-python-handler-class-will-pass-logs-to-the-uwsgi-logger). Currently there isn't really a need for that.
