### ISSUE TITLE
Switch to bootstrap 5

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#394]
As of #334 we are using crispy-forms, which should make the change somewhat easier.

Required steps:

- [x] include the new source files and exclude the old ones
- [x] change the crispy template pack to bootstrap5 (https://github.com/django-crispy-forms/crispy-bootstrap5)
- [x] change forms where we manually build the structure (e.g. qualification grants)
- [x] change bootstrap classes that have been deprecated (see https://getbootstrap.com/docs/5.0/migration/ and the existing bootstrap5 branch in this repo which is wildly outdated)
- [x] fix JS stuff (especially tooltips)
- [x] include select2 bootstrap5 theme
- [x] think about whether we still need jQuery as bootstrap does not use it anymore

**Comment by felixrindt** [comment]
I guess we still need jquery for the formset lib we are using :/
