### ISSUE TITLE
Change logging

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#400]
As a manager, I expect the home page to display the latest 42 changes that occured with a link to the complete list.

**Comment by felixrindt** [comment]
To give a bit more context to this, there are a few existing django libraries focused on the task of keeping a model history. Most of what I found when developing https://github.com/e-valuation/EvaP/pull/1424 was not focused on being able to roll back to a specific point in time. What we want though is a human-displayable log of changes.

EvaP now has a mostly out-of-the-way/automated way (on every model save) of listing changes done to a model instance, including old and new values of changed fields, which is more than django-admin does iirc. It even supports m2m relationships.

pretix also has change logging, but does that using explicit creation of LogEntry objects on form submits.

I think the EvaP solution is pretty cool, and I will look into factoring out the models in there into a single library - in the hope that it just works for us as well.

**Comment by felixrindt** [comment]
We need to decide which models to log changes for.
Events and shifts are an obvious choice, Users and Groups are probably as well, and maybe also Participations to keep track of disposition decisions. 

Keeping that all together will be difficult, and we will need to adjust the EvaP code, at least for keeping track of permission changes, right?!
