### ISSUE TITLE
daylight savings: pytz Ambigous Time Exception

### ISSUE THREAD

**Issue by felixrindt** [ephios-dev/ephios#417]
When saving the shift form with an ambiguous time, an exception is generated, e.g. creating a shift with start time

2020-10-25 at 02:30:00 (am) in Europe/Berlin.

**Comment by felixrindt** [comment]
Also, I cannot create a night shift spanning a DST-transition on 2021-10-30 with correct end time.

**Comment by jeriox** [comment]
We're back at it with the time change.
The new zoneinfo is way smarter and covers shifts that span over a DST-transition, see https://github.com/ephios-dev/ephios/pull/696#issuecomment-1061183639.

However, the error with ambigous times still persists, e.g. with the error message `2022-10-30 02:00:00 konnte mit der Zeitzone Europe/Berlin nicht eindeutig interpretiert werden, da es doppeldeutig oder eventuell inkorrekt ist.` from zoneinfo

**Comment by jeriox** [comment]
We decided on wontfix as we would need a lot of additional UI to ask the user for what they actually mean and its a very small edgecase
