### ISSUE TITLE
File storage

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#504]
As a planner, I expect to have a view where I can upload new files and delete previously uploaded files. 
As a user, I expect to have a view where I can view a list of uploaded files and download them.

Optionally:
As a planner, I want to attach a file from the file storage to an event.
As a user, I expect the event detail page to list the linked files and allow me to download them.

**Comment by Gernomaly** [comment]
Daran wäre generell Interesse vorhanden^
