### ISSUE TITLE
Manage working hours for other users

### ISSUE THREAD

**Issue by felixrindt** [ephios-dev/ephios#607]
Delete, add and edit working hours for the users you have workhours management permissions for.

Also, don't show the request button on a user profile if you have create-permissions. The CRUD views should be used instead.

**Comment by jeriox** [comment]
Do we really want to offer edit and delete views for workinghours? not sure if there is a usecase for that as they have to be confirmed anyways

**Comment by felixrindt** [comment]
> Do we really want to offer edit and delete views for workinghours? not sure if there is a usecase for that as they have to be confirmed anyways

These are meant for people with permissions to manage working hours, not your regular unprivileged user.

**Comment by jeriox** [comment]
> > Do we really want to offer edit and delete views for workinghours? not sure if there is a usecase for that as they have to be confirmed anyways
> 
> These are meant for people with permissions to manage working hours, not your regular unprivileged user.

that's how I understood it anyways. Was just not sure if there is the need for such views, because as a manager, I'd need to grant every workinghour before it is credited. so if there is a misstake or I don't want it, I can simply reject it. not sure in which case I'd want to delete it afterwards
