### ISSUE TITLE
Multiple emails sent out when creating new account

### ISSUE THREAD

**Issue by felixrindt** [ephios-dev/ephios#615]
**Describe the bug**
When creating a new user, multiple emails are sent out to that new user. A welcome mail and some about changes to the profile.

**To Reproduce**
Create a new user and check their email inbox.

**Expected behavior**
Only one email is sent, with a link to set a password.
profile change notifications are only sent when enabled and if the profile as actually changed.

**Comment by jeriox** [comment]
Can't reproduce this locally

**Comment by jeriox** [comment]
probably fixed at the point where we stopped allowing managers to set the password of the new user directly
