### ISSUE TITLE
Copy shift config

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#958]
As a planner responsible for an event that covers multiple days with the same setup each day, I don't want to enter all the details multiple times (e.g. sections and required qualifications). Instead, I want to be able to copy an exisiting shift configuration and create a similar shift on another day.

**Comment by felixrindt** [comment]
"clone shift" should work from the create event flow as well as on an existing event.

**Comment by jeriox** [comment]
related to #195, we need a proper conecpt for
- cloning events to a list of other dates
- cloning shifts to a list of other dates
- bulk-creating shifts for multiple times (maybe this can be handled by cloning to different times for a specific date?)
