### ISSUE TITLE
Export appointments as .ics file

### ISSUE THREAD

**Issue by crydotsnake** [ephios-dev/ephios#981]
**Is your feature request related to a problem? Please describe.**

It would be cool, to have the possibility to export single appointments as a .ics file. So everyone can import the specific dates into their own calendar. I know it's already possible to subscribe to the calendar. But maybe you don't want this always. Maybe you want to decide, for your self, which appointments you would like to have in your calendar.

**Describe the solution you'd like**
_None_

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

**Comment by jeriox** [comment]
Hey there, thanks for your interest in ephios!

The calender subscription only contains shifts that you are participating in, so we figured that those would be oft interest for your calendar. Could you describe your usecase a bit more in detail which events you would like to include and which not? Maybe a setting to filter the events in the subscription (e.g. by event type) could be a better approach, as .ics file have the problem of not being in sync. If the planner changes the times, your subscribed calender will be updated automatically while a single .ics file will be out of date.

**Comment by jeriox** [comment]
@crydotsnake your input would be appreciated :)
